/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/24LuSBZXgX4
 */
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"

export default function Freemium() {
  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
      <main className="p-8">
        <div className="mb-6 flex justify-between items-center">
          <h1 className="text-2xl font-semibold text-gray-800 dark:text-gray-100">KWK</h1>
          <div className="flex space-x-4 items-center">
            <Input className="w-[300%]" placeholder="Enter URL" />
            <Select>
              <SelectTrigger id="device">
                <SelectValue placeholder="Desktop" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="desktop">Desktop</SelectItem>
                <SelectItem value="mobile">Mobile</SelectItem>
              </SelectContent>
            </Select>
            <Button className="bg-gray-300 text-gray-800 hover:bg-gray-400 focus-visible:ring-gray-500 dark:bg-gray-700 dark:text-gray-200 dark:hover:bg-gray-600 dark:focus-visible:ring-gray-500">
              Get Insights
            </Button>
          </div>
        </div>
        <Tabs>
          <TabsList>
            <TabsTrigger value="real-users">Real Users</TabsTrigger>
            <TabsTrigger value="lab-data">Lab Data</TabsTrigger>
          </TabsList>
          <TabsContent className="mt-4" value="real-users">
            <div className="grid grid-cols-3 gap-6">
              <Card className="col-span-1 bg-gray-200 dark:bg-gray-800 shadow-md">
                <CardHeader>
                  <CardTitle className="text-gray-800 dark:text-gray-100">Resource Summary</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Document</span>
                      <span>120</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Total</span>
                      <span>500</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>CSS</span>
                      <span>80</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>JavaScript</span>
                      <span>200</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Images</span>
                      <span>150</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Media</span>
                      <span>50</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Fonts</span>
                      <span>30</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Other</span>
                      <span>70</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Third Party</span>
                      <span>100</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card className="col-span-2 bg-gray-200 dark:bg-gray-800 shadow-md">
                <CardHeader>
                  <CardTitle className="text-gray-800 dark:text-gray-100">Performance Metrics Summary</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Performance Score</span>
                      <span>85</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Largest Contentful Paint</span>
                      <span>2.5s</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Cumulative Layout Shift</span>
                      <span>0.1</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>First Contentful Paint</span>
                      <span>1.2s</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Speed Index</span>
                      <span>3.0s</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Total Blocking Time</span>
                      <span>0.5s</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Interaction to Next Paint</span>
                      <span>2.0s</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          <TabsContent className="mt-4" value="lab-data">
            <div className="grid grid-cols-3 gap-6">
              <Card className="col-span-1 bg-gray-200 dark:bg-gray-800 shadow-md">
                <CardHeader>
                  <CardTitle className="text-gray-800 dark:text-gray-100">Resource Summary</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Document</span>
                      <span>100</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Total</span>
                      <span>400</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>CSS</span>
                      <span>70</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>JavaScript</span>
                      <span>180</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Images</span>
                      <span>130</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Media</span>
                      <span>40</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Fonts</span>
                      <span>25</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Other</span>
                      <span>60</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Third Party</span>
                      <span>90</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card className="col-span-2 bg-gray-200 dark:bg-gray-800 shadow-md">
                <CardHeader>
                  <CardTitle className="text-gray-800 dark:text-gray-100">Performance Metrics Summary</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Performance Score</span>
                      <span>80</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Largest Contentful Paint</span>
                      <span>2.7s</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Cumulative Layout Shift</span>
                      <span>0.2</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>First Contentful Paint</span>
                      <span>1.5s</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Speed Index</span>
                      <span>3.2s</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Total Blocking Time</span>
                      <span>0.6s</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                    <div className="bg-gray-100 dark:bg-gray-700 p-4 shadow-sm flex justify-between relative">
                      <span>Time To First Byte</span>
                      <span>2.2s</span>
                      <InfoIcon className="cursor-pointer text-gray-500 dark:text-gray-400 absolute top-0 right-0 w-4 h-4" />
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
        <Button
          className="mt-4 bg-gray-300 text-gray-800 hover:bg-gray-400 focus-visible:ring-gray-500 dark:bg-gray-700 dark:text-gray-200 dark:hover:bg-gray-600 dark:focus-visible:ring-gray-500"
          onClick={undefined}
        >
          Show Page Load Screenshot
        </Button>
        <img alt="Full Page Screenshot" className="hidden" src="/full-page-screenshot.jpg" />
      </main>
    </div>
  )
}


function InfoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}
